#
# Author: Thisaru Guruge
# Website: https://ThisaruGuruge.github.io
#
# This software is under Apache 2.0 License.
#
# Copyright (c) 2020 | All Rights Reserved
#

language: shell

os: linux

jobs:
    include:
        - stage: "build"
          name: "Windows Build"
          os: windows
          language: shell
          install:
              - choco install jdk8 -params 'installdir=c:\\java8'
              - export JAVA_HOME="c:\\java8"\\
              - export PATH="$PATH;$JAVA_HOME\\bin"
              - choco install maven -version 3.6.3
              - export PATH="$PATH;C:\\ProgramData\\chocolatey\\lib\\maven\\apache-maven-3.6.3\\bin"
        - name:  "Linux Build"
          os: linux
          language: java
          jdk: openjdk8

script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mvn clean install -B -V; fi
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then powershell -C 'mvn clean install -B -V'; fi

cache:
    directories:
        - $HOME/.m2

after_success:
    - bash <(curl -s https://codecov.io/bash)
